from typing import Final

CONFIG_KEY_FREEZE_TIME_AFTER_DEATH: Final[str] = "freeze_time_after_death"
CONFIG_KEY_TICKRATE: Final[str] = "game_speed"
CONFIG_KEY_GAME_TITLE: Final[str] = "game_title"
CONFIG_KEY_SCREEN_BACKGROUND_COLOR: Final[str] = "screen_background_color"
CONFIG_KEY_GRID_STEP: Final[str] = "grid_step"
CONFIG_KEY_DRAW_GRID: Final[str] = "draw_grid"
CONFIG_KEY_GRID_COLOR: Final[str] = "grid_color"
CONFIG_KEY_SCREEN_SIZE: Final[str] = "screen_size",
CONFIG_KEY_COMMON_FOOD_EAT_POINTS: Final[str] = "common_food_eat_points",
CONFIG_KEY_BONUS_FOOD_ONLY_AFTER_X_FOODS: Final[str] = "bonus_food_after_x_foods",
CONFIG_KEY_BONUS_FOOD_CHANCE: Final[str] = "bonus_food_chance",
CONFIG_KEY_BONUS_FOOD_SCORE_POINTS: Final[str] = "bonus_food_score_points",
CONFIG_KEY_BONUS_FOOD_LIFETIME_IN_SECONDS: Final[str] = "bonus_food_lifetime_in_seconds"
CONFIG_KEY_SNAKE_INPUT_BUFFER_SIZE: Final[str] = "snake_input_buffer_size"
CONFIG_KEY_DEFAULT_FONT: Final[str] = "default_font"
CONFIG_KEY_DEFAULT_FONT_SIZE: Final[str] = "default_font_size"
CONFIG_KEY_GAME_DIFFICULTY: Final[str] = "game_difficulty"