from constants.config_keys import *
from typing import Final

game_config: Final = {
    CONFIG_KEY_GAME_TITLE: "Snake",
    CONFIG_KEY_TICKRATE: 0.01,
    CONFIG_KEY_FREEZE_TIME_AFTER_DEATH: 1,
    CONFIG_KEY_SCREEN_BACKGROUND_COLOR: "black",
    CONFIG_KEY_SCREEN_SIZE: (576, 576),
    CONFIG_KEY_DRAW_GRID: True,
    CONFIG_KEY_GRID_COLOR: "gray",
    CONFIG_KEY_GRID_STEP: 24,
    CONFIG_KEY_COMMON_FOOD_EAT_POINTS: 10,
    CONFIG_KEY_BONUS_FOOD_ONLY_AFTER_X_FOODS: 5,
    CONFIG_KEY_BONUS_FOOD_CHANCE: 0.1,
    CONFIG_KEY_BONUS_FOOD_SCORE_POINTS: 100,
    CONFIG_KEY_BONUS_FOOD_LIFETIME_IN_SECONDS: 9,
    CONFIG_KEY_SNAKE_INPUT_BUFFER_SIZE: 2,
    CONFIG_KEY_DEFAULT_FONT: "Arial",
    CONFIG_KEY_DEFAULT_FONT_SIZE: 14,
    CONFIG_KEY_GAME_DIFFICULTY: 1
}
